/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_ycsb_db_JDrdbClient */

#ifndef _Included_site_ycsb_db_JDrdbClient
#define _Included_site_ycsb_db_JDrdbClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_ycsb_db_JDrdbClient
 * Method:    initDrdbClient
 * Signature: (Ljava/lang/String;ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_site_ycsb_db_JDrdbClient_initDrdbClient
        (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     site_ycsb_db_JDrdbClient
 * Method:    destroyDrdbClient
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_JDrdbClient_destroyDrdbClient
        (JNIEnv *, jobject, jlong);

/*
 * Class:     site_ycsb_db_JDrdbClient
 * Method:    get
 * Signature: (JLjava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_site_ycsb_db_JDrdbClient_get
        (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     site_ycsb_db_JDrdbClient
 * Method:    put
 * Signature: (JLjava/lang/String;[BI)B
 */
JNIEXPORT jbyte JNICALL Java_site_ycsb_db_JDrdbClient_put
        (JNIEnv *, jobject, jlong, jstring, jbyteArray, jint);

/*
 * Class:     site_ycsb_db_JDrdbClient
 * Method:    del
 * Signature: (JLjava/lang/String;I)B
 */
JNIEXPORT jbyte JNICALL Java_site_ycsb_db_JDrdbClient_del
        (JNIEnv *, jobject, jlong, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
