services:
  server1:
    build:
      context: .
      dockerfile: dockerfiles/drdb.dockerfile
    image: "hutii/drdb:latest"
    entrypoint: "/app/build/src/distributed-rocksdb/Server/distributed-rocksdb-server-cpp -s server1 -p 13337 -c /app/src/distributed-rocksdb/Server/server_config2.txt"
    network_mode: host

  server2:
    build:
      context: .
      dockerfile: dockerfiles/drdb.dockerfile
    image: "hutii/drdb:latest"
    entrypoint: "/app/build/src/distributed-rocksdb/Server/distributed-rocksdb-server-cpp -s server2 -p 13338 -c /app/src/distributed-rocksdb/Server/server_config2.txt"
    network_mode: host

  client1:
    build:
      context: .
      dockerfile: dockerfiles/drdb.dockerfile
    image: "hutii/drdb:latest"
    entrypoint: "/app/build/src/distributed-rocksdb/Client/distributed-rocksdb-client-cpp -s server1 -p 13337"
    depends_on:
      - server1
      - server2
    network_mode: host
